### PR TITLE
Test against Ruby 2.3.1 and Rails 4.2

### PR DESCRIPTION
**Pull request by adamnbowen**
Hopefully Travis builds this 🤞

### CODE REVIEW

**Comment by tute** [comment]
It passes :)

Should it be Ruby 2.4.1? Why are we downgrading the Rails version? Should we target more than one Rails version?

Thanks for your contribution!

**Comment by adamnbowen** [comment]
Sorry, this was intended to be on our own fork—I didn't intend to downgrade the official repository ;)

**Comment by tute** [comment]
Send patches our way and we can work together! ❤️

**Comment by adamnbowen** [comment]
That's our intention, though you will likely disagree with one of the big ones we want to tackle—we want to remove Ambry, since we'd rather keep everything in Postgres.  But we're happy to contribute back things that are useful to your repository as well.  This branch was just me testing I had the Travis CI setup correctly, but I'll probably submit a different one with Ruby 2.3, 2.4 and Rails 4.2 and 5 if that's something you're interested in.

**Comment by tute** [comment]
> I'll probably submit a different one with Ruby 2.3, 2.4 and Rails 4.2 and 5 if that's something you're interested in.

Absolutely, please do! A related comment: https://github.com/merit-gem/merit/pull/266#issuecomment-258267413

**Pull request closed without merging**
