### PR TITLE
Score points support bigint

### LINKED ISSUE #173: warning: already initialized constant Merit::AppBadgeRules
I get the following error while initializing rails console/server while using Merit ~> 2.0. The same warning existing since Merit 2.0.0.

```
~/project (master) ⚡ rails c
/Library/Ruby/Gems/2.0.0/gems/merit-2.1.1/lib/merit.rb:83: warning: already initialized constant Merit::AppBadgeRules
/Library/Ruby/Gems/2.0.0/gems/merit-2.1.1/lib/merit.rb:83: warning: previous definition of AppBadgeRules was here
/Library/Ruby/Gems/2.0.0/gems/merit-2.1.1/lib/merit.rb:84: warning: already initialized constant Merit::AppPointRules
/Library/Ruby/Gems/2.0.0/gems/merit-2.1.1/lib/merit.rb:84: warning: previous definition of AppPointRules was here
Loading development environment (Rails 4.0.0)
```

### PR DESCRIPTION
**Pull request by xofred**
BUGFIX
- Fix Rails 5 sash validation fail
- Fix #173 

FEATURE
- Support score points bigint

### CODE REVIEW

**Comment by xofred** [comment]
These three were issues we met in production
1. Without `optional: true` in model definition, Rails 5 will complain about the parent model can't be nil
2. Base on the commit date of the fix, and yes, it seems still an issue...
3. Our production project has been running since November last year, and seems no errors caused by changing `int` to `bigint`

**Comment by tute** [comment]
Thanks!

> * Without `optional: true` in model definition, Rails 5 will complain about the parent model can't be nil

Can you write a regression test for this? Does it fail in Rails 5.2 as well?

> * yes, it seems still an issue...

Do you know why #282 doesn't fix it for you?

> * Our production project has been running since November last year, and seems no errors caused by changing `int` to `bigint`

:+1:

**Comment by tute** [comment]
@xofred thanks for your contribution! We can incorporate the `bigint` change if you'd like, as it doesn't require regression tests to be added to the PR. If you'd like to leave only that change, put a good commit message around it and rebase the branch, I'll get it merged. Thanks! Happy weekend.

**Comment by xofred** [comment]
@tute Just keeping only the bigint changes, and rebased with https://github.com/merit-gem/merit. Should be good to go :)

**Pull request merged**
