### PR TITLE
Accept only integers in add_badge

### PR DESCRIPTION
**Pull request by itsdan**
```ruby
badge = Merit::Badge.first
current_user.add_badge(1) # => OK
current_user.add_badge(badge) # => NoMethodError
```

### CODE REVIEW

**Comment by tute** [comment]
Hey @itsdan!

* This would be a bit inconsistent with the Rails' APIs, that allow the id or object in ActiveRecord calls.
* `NoMethodError` doesn't seem to be the right exception for a type error.

Why would you prefer an API that only allows the integer version? Thanks!

**Comment by itsdan** [comment]
Hello, @tute!
```ruby
current_user.add_badge(1)
current_user.badges # => [#<Merit::Badge id: 1, name: "badge", level: nil, description: "Description.", custom_fields: nil>]
current_user.badges.count # => 1
```

```ruby
badge = Merit::Badge.first # => #<Merit::Badge id: 1, name: "badge", level: nil, description: "Description.", custom_fields: nil>
another_user.add_badge(badge) # => #<Merit::BadgesSash:0x007ffad08aed78
another_user.badges # => [#<#<Class:0x007ffacc9fa2f8>:0x007ffad0852ed8
another_user.badges.first # => #<#<Class:0x007ffacc9fa2f8>:0x007ffad0277d38
another_user.badges.first.class # => #<Class:0x007ffacc9fa2f8>
another_user.badges.first.id # NoMethodError: undefined method `id' for #<#<Class:0x007ffacc9fa2f8>:0x007fface45c330>
```

Is this the desired behaviour? After adding an object to player's badges I receive an array of unknown objects, I cannot call `Badge` methods on its elements.

**Comment by tute** [comment]
That's not expected, this seems like a bug. Can you isolate the problem with a failing test? Do you know why this happens? Thank you!

**Comment by tute** [comment]
ping @itsdan

**Comment by tute** [comment]
ping @itsdan

**Comment by tute** [comment]
Now I see the problem:

```
irb(main):003:0> user.add_badge Merit::Badge.find(1)
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
   (0.0ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "sashes" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-04-25 03:04:35.894410"], ["updated_at", "2015-04-25 03:04:35.894410"]]
  SQL (0.1ms)  INSERT INTO "merit_scores" DEFAULT VALUES
  SQL (0.1ms)  UPDATE "merit_scores" SET "sash_id" = ? WHERE "merit_scores"."id" = ?  [["sash_id", 1], ["id", 1]]
   (1.4ms)  commit transaction
   (0.1ms)  begin transaction
  SQL (0.2ms)  UPDATE "users" SET "sash_id" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["sash_id", 1], ["updated_at", "2015-04-25 03:04:35.907212"], ["id", 1]]
   (0.7ms)  commit transaction
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "badges_sashes" ("sash_id", "created_at") VALUES (?, ?)  [["sash_id", 1], ["created_at", "2015-04-25 03:04:35.912220"]]
   (0.7ms)  commit transaction
=> #<Merit::BadgesSash id: 1, badge_id: nil, sash_id: 1, notified_user: false, created_at: "2015-04-25 03:04:35">
```

We allow the creation of a `BadgesSash` with no badge id! Will merge this as a temporary bug fix, although it doesn't fix the awkward API. Thanks for your work!

**Pull request merged**
