### PR TITLE
Replace update attributes with update and add new ruby version builds

### PR DESCRIPTION
**Pull request by jamesjefferies**
Rails 6.0 deprecation notice - that update_attributes will be deprecated. Replace calls with update - https://github.com/rails/rails/pull/31998

```DEPRECATION WARNING: update_attributes is deprecated and will be removed from Rails 6.1```

### CODE REVIEW

**Comment by tute** [comment]
Yay, thank you! Should we bring back testing against `master` Rails, so we make sure everything else works and we see other deprecations that might happen? https://github.com/merit-gem/merit/commit/dd7b05a473f2781d2e6ed8452bd01451fc6d02a1#diff-354f30a63fb0907d4ad57269548329e3

**Comment by tute** [comment]
And apparently we need to add sqlite3 for Rails 5.1 to pass? I'm fine with doing that as part of this or another independent PR. Thank you again!

**Comment by jamesjefferies** [comment]
Hmm, hitting a few issues around minitest-rails (which hasn't been updated in a while) - maybe this PR should focus on rails 5.1 and 5.2 for now...

**Comment by tute** [comment]
:disappointed: maybe we wait then, given in Rails <6 this wouldn't be necessary yet. Thank you @jamesjefferies, and let's come back to this soon!

**Comment by jamesjefferies** [comment]
@tute hi - this version now ignores Rails 6, but builds against new versions of Ruby and Rails 5.1 and 5.2 - which I think is fair enough.

**Comment by tute** [comment]
Thank you, @jamesjefferies! I combined the commits together, updated the commit message, and merged it in. :tada:

**Comment by jamesjefferies** [comment]
Great - thanks @tute !

**Pull request merged**
