### PR TITLE
Optimistic engine rules loading

### PR DESCRIPTION
**Pull request by hugobast**
Fix: #267

The test passes and the goal of being noisy on failures is met. This is probably wrong in other ways that I fail to see. Let me know what you think.

### CODE REVIEW

**Comment by tute** [comment]
Hi, thanks! We still need the `rescue`, as of https://github.com/merit-gem/merit/issues/39.

We can have two `begin`/`rescue` blocks to address your use case, and add the context of why it exists in the commit message.

Thanks for sharing your work!

**Comment by hugobast** [comment]
One of the consequence of the begin/rescue that was there before, is that if either rules classes was undefined we would then skip over this line `include Merit::ControllerExtensions`. Looking at the console you wouldn't be able to tell that the configuration was halted. Can you tell me what ideally should happen if you don't define any rules classes? Should we have default rules classes somewhere or generated from a rake task instead?

I'm saying all this because if we are missing any one of the 2 rules class then `include Merit::ControllerExtensions` this include generates other harder to figure out errors as the output.

**Comment by tute** [comment]
> We can have two begin/rescue blocks to address your use case, and add the context of why it exists in the commit message.

**Comment by tute** [comment]
I see the issue here. What do you think of my suggested solution?

> We can have two begin/rescue blocks to address your use case, and add the context of why it exists in the commit message.

This would force users to always define both classes, allowing us to catch either problematic case, or both.

**Comment by hugobast** [comment]
I'll have to give it a go, I don't remember what I tried after your first comment but I didn't really like it.
Although another solution could be to warn users somehow or tell them more explicitly that both classes are required for this library to do it's job.

**Comment by tute** [comment]
@hugobast, I'll close this PR because it introduces a different bug, and due to lack of activity. If you'd like to continue work on it, we reopen and do work on it.
Thanks for sharing ideas for improvement and your work! 😃 ❤️

**Pull request closed without merging**
