### PR TITLE
Fixes Rails autoloader deprecation warning

### LINKED ISSUE #331: DEPRECATION WARNING: Initialization autoloaded the constant Merit::Badge.
Hello,

Just started a new app with Rails `6.0.0.rc1` (and Merit) and got a deprecation notice when running tests via `rspec`:

```
DEPRECATION WARNING: Initialization autoloaded the constant Merit::Badge.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Merit::Badge, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
```

There is some discussion about a similar notice [here](https://github.com/rails/rails/issues/36363).

### PR DESCRIPTION
**Pull request by jairovm**
Fixes #331

### CODE REVIEW

**Comment by tute** [comment]
Thanks! The build now fails with:

```NameError: undefined local variable or method `extend_orm_with_has_merit' for #<#<Class:0x0000000002a12e38>:0x0000000003c9a4c0 @locked=false>
/home/travis/build/merit-gem/merit/lib/merit.rb:65:in `block (2 levels) in <class:Engine>'```

How can we make it pass?

**Comment by tute** [comment]
Thanks! The build now fails with:

```NameError: undefined local variable or method `extend_orm_with_has_merit' for #<#<Class:0x0000000002a12e38>:0x0000000003c9a4c0 @locked=false>
/home/travis/build/merit-gem/merit/lib/merit.rb:65:in `block (2 levels) in <class:Engine>'```

Can you make CI pass?

**Comment by jairovm** [comment]
@tute tests passed, let me know if you want me to change something else, thanks

**Comment by tute** [comment]
Thanks! I just tested it, but when I launch the `rails console`, I still see the warning in the `log/development.log` file. This doesn't seem to fix that issue.

**Comment by jairovm** [comment]
Actually, I just re-read the related issue and it looks like there's another Deprecation Warning I wasn't aware of 
```
DEPRECATION WARNING: Initialization autoloaded the constant Merit::Badge.
```

This PR fixes this deprecation message ( Merit::BadgeRules, and Merit::PointRules are the ones we care about ).
```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper, ActionText::TagHelper, 
Merit::BadgeRules, and Merit::PointRules.
```

In order to see that message `ActiveSupport.on_load(action_controller_hook)` event should be triggered, here is what I did: 
```
rails new merit --skip-spring
cd merit

echo "ActionController::Base" > config/initializers/action_controller.rb
echo "gem 'merit', '4.0.1'" >> Gemfile
bundle install
rails g merit:install
rails db:migrate

rails runner 1 # warning message added to tmp/development.log
```

When doing the same on my fix, this is what I get ( Merit::BadgeRules, and Merit::PointRules are not there anymore )
```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.
```

I changed my Gemfile to pull `merit` gem from my github
```
gem 'merit', git: 'https://github.com/jairovm/merit.git', ref: '31bcf79'
```

**Comment by jairovm** [comment]
Regarding of `Merit::Badge` deprecation warning, I think that's caused because this being added to an initializer
```ruby
# config/initializers/merit.rb

Merit::Badge.create!(
  id: 1,
  name: "year-member",
  description: "Active member for a year",
  custom_fields: { difficulty: :silver }
)
```

It should look something like this ( as specified in the logs )

```ruby
# config/initializers/merit.rb

Rails.application.reloader.to_prepare do
  Merit::Badge.create!(
    id: 1,
    name: "year-member",
    description: "Active member for a year",
    custom_fields: { difficulty: :silver }
  )
end
```

I can update the Readme if you want.

**Comment by burmashave** [comment]
I had the same problem and solved it exactly as @jairovm suggested: by wrapping everything with `Rails.application.reloader.to_prepare`

See: https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots

**Comment by tute** [comment]
> This PR fixes this deprecation message ( Merit::BadgeRules, and Merit::PointRules are the ones we care about ).

Got it, thanks! I saw it, good to merge already.

> I can update the Readme if you want.

Yes, please! Want to do that as part of this PR or a new one?

Thank you both.

**Comment by jairovm** [comment]
Just changed it within this PR 😅. Thanks @tute

**Comment by tute** [comment]
Thank you!!

**Pull request merged**
